Fix package name used in zanata check
rhinstaller/python-meh pull request #26
Opened 2020-02-25 14:49 UTC by VladimirSlavik

SSIA. Reason - no python2 version of zanata on f31.

2020-02-25 16:05 UTC, poncovka approved these changes
Looks good to me.

2020-02-26 18:09 UTC, jkonecny12 requested changes
Same old story of testing exact package presence. Please change this according to:

https://github.com/pykickstart/pykickstart/blob/ca26e432653f3334b8ed29fcdd92dd32e4f5c066/Makefile#L22

It's much better to test if command is present than package is present.

2020-02-27 09:55 UTC, VladimirSlavik commented
Changed according to review.

2020-02-27 16:06 UTC, jkonecny12 approved these changes
Looks good to me now.

2020-02-28 10:34 UTC, VladimirSlavik commented
Resolved by #24 so this is not needed any more.

2020-02-28 10:34 UTC, closed without merging